sudo: required
language: android
android:
 components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
before_install:
 - yes | ${ANDROID_HOME}/tools/bin/sdkmanager "platforms;android-26"
before_script:
 - chmod +x generate-apk.sh
script:
 - ./gradlew assembleDebug # Change this to "gradlew build" once lint issues are fixed. Also update generate-apk.sh accordingly
after_success:
 - ./generate-apk.sh
